pi.all <- read.table("xenopus_NDiv.windowed.pi",header=T)
hist(pi.all$PI,br=20)
boxplot(pi.all$PI,ylab="Nucleotide diversity")

names(pi.all)
attach(pi.all)
levels(CHROM)
pi.chr1L <- subset(pi.all, CHROM == "chr1L", PI)
nrow(pi.chr1L)
nrow(pi.all)
head(pi.chr1L)
head(pi.all)
tail(pi.chr1L)
tail(pi.all)
summary(pi.chr1L)
summary(pi.all)
plot(pi.chr1L$PI,xlab="Position on chr1L",ylab="Nucleotide diversity Pi", col = ifelse(pi.chr1L$PI < 4.333e-05,'black','red'))
plot(pi.chr1L$PI,xlab="Position on chr1L",ylab="Nucleotide diversity Pi", col = ifelse(pi.chr1L$PI < 6.691e-05,'black','blue'))

